app/models.py
from app import db, login
from flask_login import UserMixin # IS ONLY FOR THE USER MODEL!!!!
from datetime import datetime as dt
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import CheckConstraint

class Cart(db.Model):
    item_id = db.Column(db.Integer, db.ForeignKey('item.item_id'), primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)




class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name =  db.Column(db.String)
    email =  db.Column(db.String, unique=True, index=True)
    password =  db.Column(db.String)
    created_on = db.Column(db.DateTime, default=dt.utcnow)
    cart = db.relationship('Item',
        secondary = 'cart',
        backref = 'users',
        lazy = 'dynamic'
    )

    # should return a unique identifing string
    def __repr__(self):
        return f'<User: {self.email} | {self.id}>'

    # Human readbale ver of rpr
    def __str__(self):
        return f'<User: {self.email} | {self.first_name} {self.last_name}>'

    #salts and hashes our password to make it hard to steal
    def hash_password(self, original_password):
        return generate_password_hash(original_password)

    # compares the user password to the password provided in the login form
    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)

    def from_dict(self, data):
        self.first_name = data['first_name']
        self.last_name = data['last_name']
        self.email=data['email']
        self.password = self.hash_password(data['password'])

    def add_to_cart(self, item):
        self.cart.append(item)
        db.session.commit()

    def remove_all(self, cart):
        for item in cart:
            self.cart.remove(item)
            db.session.commit()

    def remove_item(self, item):
        if self.cart:
            self.cart.remove(item)
            db.session.commit()

    # save the user to the database
    def save(self):
        db.session.add(self) #adds the user to the db session
        db.session.commit() #save everythig in the session to the db

class Item(db.Model):
    item_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    desc = db.Column(db.Text)
    price = db.Column(db.Float)
    img=db.Column(db.String)
    created_on=db.Column(db.DateTime, index=True, default=dt.utcnow)



    def __repr__(self):
        return f'<Item: {self.item_id}|{self.name}'

    def delete_item(self):
        db.session.delete(self)
        db.session.commit()
    def save(self):
        db.session.add(self)
        db.session.commit()

    def to_dict(self):
        return {
            'id':self.id,
            'name':self.name,
            'desc':self.desc,
            'price':self.price,
            'img':self.img,
            'created_on':self.created_on
        }

    def from_dict(self, data):
        for field in ['name','desc','price','img']:
            if field in data:
                    #the object, the attribute, value
                setattr(self, field, data[field])


    
@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from sqlalchemy import LABEL_STYLE_TABLENAME_PLUS_COL
from wtforms import StringField, SubmitField, DecimalField, URLField
from wtforms.validators import DataRequired

class ItemForm(FlaskForm):
    name = StringField('Item Name', validators= [DataRequired()])
    desc = StringField('Description', validators= [DataRequired()])
    price = DecimalField('Price', validators= [DataRequired()])
    img = URLField('Image URL', validators= [DataRequired()])
    submit = SubmitField('Post')

class AddToCart(FlaskForm):
    submit = SubmitField('Add To Cart')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment


# Register Plug-ins
login = LoginManager()

#init my Database manager
db = SQLAlchemy()
migrate = Migrate()
moment = Moment()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    #Configure Some Settings
    login.login_view = 'auth.login'
    login.login_message = 'You have to log in!'
    login.login_message_category='warning'

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)



    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='')

from . import routes

app/blueprints/main/routes.py
from .import bp as main
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from app.models import Item, User, Cart
from .forms import ItemForm

# ROUTES
@main.route('/', methods = ['GET'])
@login_required
def index():
    return render_template('index.html.j2')

@main.route('/post', methods = ['GET', 'POST'])
@login_required
def post():
    form = ItemForm()
    if request.method == 'POST' and form.validate_on_submit():
        item_data = {
            "name" :form.name.data,
            "desc" : form.desc.data,
            "price" : form.price.data,
            "img" :form.img.data
        }
        new_item = Item()
        new_item.from_dict(item_data)
        new_item.save()
        flash('You have successfully added you item', 'success')
        return redirect(url_for('main.post'))
    return render_template('post.html.j2', form=form)

@main.route('/add_item/<int:item_id>', methods = ['GET', 'POST'])
@login_required
def add_item(item_id):
    item = Item.query.get(item_id)
    current_user.add_to_cart(item)
    Cart(item_id=item_id, user_id = current_user.id )
    flash(f'You have added item to cart.', "success")
    return redirect(request.referrer or url_for('main.item', item= item))
       
@main.route('/remove_item/<int:item_id>', methods = ['GET', 'POST'])
@login_required
def remove_item(item_id):
    item = Item.query.filter_by(item_id=item_id).first()
    current_user.remove_item(item)
    flash(f'You have removed item from cart.', "success")
    return redirect(request.referrer or url_for('main.cart',item= item))

@main.route('/remove_all' , methods = ['GET', 'POST'])
@login_required
def remove_all():
    cart = current_user.cart
    current_user.remove_all(cart)
    flash(f'You have removed all items from cart.', "success")
    return redirect(request.referrer or url_for('main.cart',item= item))
 
  
@main.route('/cart', methods = ['GET', 'POST'])
@login_required
def cart():
    cart = current_user.cart
    
    return render_template('cart.html.j2',cart=cart)

@main.route('/shop', methods = ['GET', 'POST'])
def shop():
    items = Item.query.all()


    return render_template('main_store.html.j2',items = items)

@main.route('/get_item/<int:item_id>', methods = ['GET', 'POST'])
@login_required
def get_item(item_id):
    item = Item.query.get(item_id)

    return render_template('get_item.html.j2',item=item)

@main.route('/pay', methods = ['GET', 'POST'])
@login_required
def pay():
    total = []
    cart = current_user.cart
    for item in cart:
        price = item.price
        total.append(price)

    total = sum(total)


    return render_template('payment.html.j2',total=total)

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='images/favicon-16x16.png')}}">
    <link rel="manifest" href="{{url_for('static', filename='images/site.webmanifest')}}">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Koulen&display=swap');
    </style>
    
    {% block css %}
    
    {% endblock %}
    {# {{ moment.include _moment()}} #}
    <title>STORE - {% block title %}{% endblock %}</title>

</head>
<body>
    {% include './includes/nav.html.j2' %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for class, message in messages %}
                <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container chakra">
        {% block content%}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/cart.html.j2
{% extends "base.html.j2" %}
{% block title %}
Cart
{% endblock %}
{% block content%}
{%for item in current_user.cart%}
{% include './includes/item.html.j2' %}
<br>
{%endfor%}
<a href="{{url_for('main.remove_all')}}" class="btn btn-primary form-control ">Empty Cart</a>
<br>
<br>
<a href="{{url_for('main.pay')}}" class="btn btn-primary form-control">Pay</a>

{% endblock %}

app/templates/get_item.html.j2
{% extends "base.html.j2" %}
{% block title %}
Item
{% endblock %}
{% block content%}

{% include './includes/item.html.j2' %}

    

{% endblock %}

app/templates/includes/item.html.j2
<div class="card" style="width: 18rem;">
  <img src="{{item.img}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{item.name.title()}}</h5>
    <p class="card-text">{{item.desc}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">${{item.price}}</li>
    <li class="list-group-item">{{item.created_on}}</li>
  </ul>
  <div class="card-body">
    <a href="{{url_for('main.get_item', item_id= item.item_id)}}" class="card-link">See Item</a>
    {%if item in cart%}
    <a href="{{url_for('main.remove_item', item_id= item.item_id)}}" class="card-link">Remove</a>
    {%else%}
    <a href="{{url_for('main.add_item', item_id= item.item_id)}}" class="card-link">Add To Cart</a>
    {%endif%}
  </div>
</div>

app/templates/includes/nav.html.j2
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src = "https://res.cloudinary.com/dipcloqy3/image/upload/v1652678243/10_KICKS_LogoBlue_cvvjh6.gif" style = "height:80px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {%if current_user.is_authenticated%}
                <a class="nav-link active chakra" aria-current="page" href="/">Home</a>
                <a class="nav-link chakra" href="{{url_for('main.shop')}}">Shop</a>
                <a class="nav-link chakra" href="{{url_for('main.post')}}">Post Item</a>
                

                {%else%}
                <a class="nav-link chakra" href="{{url_for('main.shop')}}">Shop</a>
                <a class="nav-link chakra" href="{{url_for('auth.login')}}">Login</a>
                <a class="nav-link chakra" href="{{url_for('auth.register')}}">Register</a>
                {%endif%}
            </div>
                {% if current_user.is_authenticated %}
                <ul class="navbar-nav ms-auto align-items-center">
    
                <li class="nav-item">
                <div class="row">
                <div class="col-12">    
                    <a class="nav-link d-flex justify-content-center" href="{{url_for('main.cart')}}"><i class="bi bi-cart text-danger" style="font-size: 1.5rem"></i></a>
                </div>
                <div class="col-12">
                    <a class="nav-link d-flex justify-content-center" href="{{url_for('auth.logout')}}"><i class="bi bi-box-arrow-right text-danger" style="font-size: 1.5rem"></i></a>
                </div>
                </div>
                    
                </li>
                </ul>
                {% endif %}
            </div>

    </div>
    </nav>

app/templates/index.html.j2
{% extends "base.html.j2" %}
{% block title %}
Home
{% endblock %}
{% block content%}

<h1>Welcome to my amazing site that i took forever to make</h1>

    

{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}
{% block title %}
Login
{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="{{url_for('auth.login')}}" method = "POST">

  {{form.hidden_tag()}}
  <div>
  {{form.email.label(class="form-label")}}
  {{form.email(class="form-control bg-secondary")}}
  {% for error in form.email.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>
  <br>
  <div>
  {{form.password.label(class="form-label")}}
  {{form.password(class="form-control bg-secondary")}}
  {% for error in form.password.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>
  <br>
  <div>
  {{form.submit(class="btn btn-primary form-control")}}
  </div>
</form>
{% endblock %}

app/templates/main_store.html.j2
{% extends "base.html.j2" %}
{% block title %}
Shop
{% endblock %}
{% block content%}

{%for item in items%}
{% include './includes/item.html.j2' %}

{%endfor%}
    

{% endblock %}

app/templates/payment.html.j2
{% extends "base.html.j2" %}
{% block title %}
Payment
{% endblock %}
{% block content%}

<div>
    <h2>Total</h2>
    <br>
    <h2>{{total}}</h2>
</div>

    

{% endblock %}

app/templates/post.html.j2
{% extends "base.html.j2" %}
{% block title %}
Post
{% endblock %}
{% block content%}
<h1>Post</h1>
<form action="{{url_for('main.post')}}" method = "POST">

  {{form.hidden_tag()}}
  <div>
  {{form.name.label(class="form-label")}}
  {{form.name(class="form-control bg-secondary")}}
  </div>
  <br>
  <div>
  {{form.price.label(class="form-label")}}
  {{form.price(class="form-control bg-secondary")}}
  </div>
  <br>
  <div>
  {{form.img.label(class="form-label")}}
  {{form.img(class="form-control bg-secondary")}}
  </div>
  <br>
  <div>
  {{form.desc.label(class="form-label")}}
  {{form.desc(class="form-control bg-secondary")}}
  </div>
  <br>
  <div>
  {{form.submit(class="btn btn-primary form-control")}}
  </div>
</form>

{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2' %}
{% block title %}

  {%if current_user.is_authenticated%}
    Edit Profile
  {%else%}
    Register
  {%endif%}

{% endblock %}

{% block content %}
<h1>
  {%if current_user.is_authenticated%}
    Edit Profile
  {%else%}
    Register
  {%endif%}
</h1>
<form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.register')}}" method = "POST">

  {{form.hidden_tag()}}

  <div>
  {{form.first_name.label(class="form-label")}}
  {{form.first_name(class="form-control bg-secondary")}}
  {% for error in form.first_name.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>
<div>
  {{form.last_name.label(class="form-label")}}
  {{form.last_name(class="form-control bg-secondary")}}
  {% for error in form.last_name.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <div>
  {{form.email.label(class="form-label")}}
  {{form.email(class="form-control bg-secondary")}}
  {% for error in form.email.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <br>
  <div>
  {{form.password.label(class="form-label")}}
  {{form.password(class="form-control bg-secondary")}}
  {% for error in form.password.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <div>
  {{form.confirm_password.label(class="form-label")}}
  {{form.confirm_password(class="form-control bg-secondary")}}
  {% for error in form.confirm_password.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>
  
  <br>
  <div>
  {{form.submit(class="btn btn-primary form-control btn-outline-warning")}}
  </div>

</form>
{% endblock %}